name: Test de Conexión GCP

on: 
  push:
    branches: [ "develop" ]
  workflow_dispatch: # Esto permite que lo actives manualmente con un clic

jobs:
  verificar-acceso:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # OBLIGATORIO

    steps:
      - uses: actions/checkout@v4

      # 1. Intentamos entrar
      - name: Autenticación con Google
        id: auth
        uses: google-github-actions/auth@v2
        with:
          # Tus datos exactos (Ya los tengo de tus logs anteriores)
          workload_identity_provider: 'projects/414435283954/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-deploy-sa@restomap-478918.iam.gserviceaccount.com'

      # 2. Si entramos, preguntamos "quién soy" para confirmar
      - name: Verificar Identidad
        run: |
          echo "¡Conexión Exitosa!"
          gcloud auth list
          gcloud projects describe restomap-478918
